---
- hosts: all
  user: root

  vars:
    console_keymap: en
    console_font: eurlatgr
    system_locale: en_US.UTF-8
    system_timezone: Europe/Madrid
    root_shell: /bin/bash
    domain: "{{ ansible_nodename.split('.')[1:] | join('.') }}"
    keys:
      - key: "{{ sshkey }}"

  tasks:
    - name: Include base tasks
      include_tasks: "{{item}}"
      with_fileglob:
        - "tasks/base/*.yaml"

    - name: Flush handlers
      meta: flush_handlers

  handlers:
    - name: Restart monit
      service:
        name: monit
        state: restarted
      when: monit

    - name: Restart systemd
      shell: systemctl daemon-reload

    - name: Restart sshd
      service:
        name: sshd
        state: restarted
