apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: common-pre-flight-spokes
  annotations:
    description: |
      This task will execute a quick check of some pre-requirements, like binaries, files, etc...
spec:
  workspaces:
    - name: ztp
  params:
    - name: ztp-container-image
      type: string
      default: "quay.io/ztpfw/pipeline:latest"
    - name: spokes-config
      type: string
      default: ""
    - name: kubeconfig
      type: string
      default: ""
    - name: mock
      type: string
      default: "false"
  stepTemplate:
    env:
      - name: WORKDIR
        value: "/workspace/ztp"
      - name: KUBECONFIG
        value: $(params.kubeconfig)
      - name: SPOKES_CONFIG
        value: $(params.spokes-config)
      - name: SHARED_DIR
        value: "shared-utils"
      - name: MOCK
        value: $(params.mock)
  steps:
    - name: common-pre-flight
      image: "$(params.ztp-container-image)"
      imagePullPolicy: Always
      script: |
        #!/usr/bin/bash
        if [[ "${MOCK}" == 'false' ]]; then
          cp -r /opt/ztp/* ${WORKDIR}/
          mkdir -p ${WORKDIR}/build
          cd ${WORKDIR}/${SHARED_DIR}
          ./verify_preflight.sh
          ./verify_preflight-spokes.sh
        else
          echo "Common Preflight Spoke: Mock mode on"
        fi
