- name: Install helpful packages
  package: name={{ item }} state=present
  with_items:
    - chrony

  ignore_errors: true

- name: Enable helpful services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - firewalld
  ignore_errors: true

- name: Force time sync
  shell: chronyc -a 'burst 4/4'
