- name: Install helpful packages
  package: name={{ item }} state=present
  with_items:
    - fail2ban
  ignore_errors: true
  when: sshpassword==True

- name: Configure fail2ban for SSH
  ini_file:
    path: /etc/fail2ban/jail.conf
    section: sshd
    option: enabled
    value: true

- name: Enable helpful services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - fail2ban
  when: sshpassword==True

- name: Disable helpful services
  service: name={{ item }} enabled=no state=stopped
  with_items:
    - fail2ban
  when: sshpassword==false
  ignore_errors: true
